// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildSplits(arg1:Array<main.SplitLine>,arg2:boolean):Promise<string>;

export function DownloadIcons():Promise<string>;

export function FixLiveSplit():Promise<string>;

export function GetIcon(arg1:string):Promise<string>;

export function GetOptions():Promise<Array<main.Option>>;

export function GetSplits(arg1:string):Promise<main.GetSplitsResult>;

export function GetTemplates():Promise<Array<main.Option>>;

export function GetTranslateData():Promise<string>;

export function LoadSplitFile(arg1:string):Promise<Array<main.SplitLine>>;

export function SaveIconsZip():Promise<void>;

export function SaveSplitsFile(arg1:Array<main.SplitLine>,arg2:boolean):Promise<void>;
